#!/usr/bin/env bash
#
# pxltrm - A pixel art editor for the terminal.


clear_screen() {
    printf '\e[2J\e[2;0H\e[0m'
    history+=("$_")
}

get_term_size() {
    shopt -s checkwinsize; (:;:)

    [[ -z "$LINES" || -z "$COLUMNS" ]] && \
        read -r LINES COLUMNS < <(stty size)
}

print_palette() {
    for i in {1..8}; do
        [[ "$i" == "$color" ]] && block_char="▃" || block_char=" "
        status+="\\e[48;5;${i}m\\e[30m${block_width// /${block_char}}\\e[0m"
    done
}

status_line() {
    local status

    printf -v block_width "%$((COLUMNS / 24))s" ""
    printf -v padding "%b" "\\e[$((COLUMNS - COLUMNS / 3))C"

    print_palette
    print_color

    # Top status bar.
    hud="[d]raw, [e]rase, clea[r], [s]ave, [o]pen, e[x]it "
    hud="${hud//\[/\[\\e[1m}"
    printf '\e[s\e[0;0H\e[0m%b' "${hud//\]/\\e[0m\]}"

    # Bottom status bar.
    printf '\e[%s;0H\e[0m%b\e[0m, %b\e[0m\e[99999D%b\e[1A\e[%sD%b\e[u' \
           "$((LINES-2))" \
           "[\\e[1mc\\e[0m]olor: ${print_col}${color}" \
           "[\\e[1mb\\e[0m]rush: \\e[1m${brush_char:=█}" \
           "${padding}${status}" \
           "$COLUMNS" \
           "${padding}${status//▃/ }"
}

status_line_clean() {
    printf '%b' "\\e[s\\e[$((LINES-3));0H\\e[0J\\e[u"
}

save_file() {
    [[ -z "$1" ]] && return
    printf '%b\n' "\\e[2J\\e[2;0H${history[*]}\\e[0m\\e[99999;0H" > "$1"
    printf '\e[%s;0H%s' "$((LINES-1))" "File saved in $1"
}

load_file() {
    clear_screen
    load_file="$1"
    file_data="$(<"$1")"
    printf '%b' "\\e[2;0H${file_data}\\e[2;0H"
    history+=("$file_data")
    status_line
}

hex_to_rgb() {
    ((r=16#${color:1:2}))
    ((g=16#${color:3:2}))
    ((b=16#${color:5:6}))
}

print_color() {
    case "${color:=7}" in
        "#"*) hex_to_rgb;: "\\x1b[38;2;${r};${g};${b}m" ;;
        [0-9]*):           "\\e[38;5;${color}m" ;;
        *):                "\\e[38;5;7m"
    esac
    printf -v print_col '%b' "\\e[1m$_"
}

prompt() {
    printf '\e[s\e[%s;0H\e[0m' "$((LINES-1))"

    case "$1" in
        s) read -rp "save file: " file; save_file "${file:-$load_file}" ;;
        o) read -rp "load file: " file; [[ -f "$file" ]] && load_file "$file" ;;
        c) read -rp "input color: " color ;;
        b) read -rp "input brush: " brush_char ;;
    esac

    printf '\e[u'
    status_line_clean
    status_line
}

paint() {
    IFS='[;' read -p $'\e[6n' -d R -rsa pos
    printf '%b' "\\e[${pos[1]};${pos[2]}H${2}${1}"
    history+=("$_")
}

cursor() {
    case "${1: -1}" in
        # Cursor Movement.
        A|k) printf '\e[1A' ;;
        B|j) printf '\e[1B' ;;
        C|l) printf '\e[1C' ;;
        D|h) printf '\e[1D' ;;

        # Line movement.
        H) printf '\e[999999D' ;;
        L) printf '\e[999999C' ;;

        # Color Selection.
        [1-8]) color="${1: -1}";  status_line ;;
        c)     prompt "${1: -1}"; status_line ;;

        # Drawing Cells.
        e) paint " " ;;
        d) print_color; paint "${brush_char:=█}" "$print_col" ;;

        # Brushes
        b) prompt "${1: -1}"; status_line ;;

        # Saving/Loading
        s|o) prompt "${1: -1}" ;;

        # Other.
        r) clear_screen; status_line ;;
        x) exit ;;
    esac
}

main() {
    clear_screen
    get_term_size
    status_line

    trap 'clear_screen' EXIT
    trap 'status_line_clean; get_term_size; status_line' SIGWINCH

    for ((;;)); { read -rs -n 1 key; cursor "$key"; }
}

main "$@"
